from django.urls import path
from . import views

urlpatterns = [
    path('admin_dashboard/', views.admin_dashboard, name='admin_dashboard'),
    path('user_management', views.user_management, name='user_management'),
    path('delete_user/<user_id>', views.delete_user, name='delete_user'),
    path('product_management', views.product_management, name='product_management'),
    path('category_management', views.category_management, name='category_management'),
    path('admin_login/', views.admin_login, name='admin_login'),
    path('admin_logout', views.admin_logout, name='admin_logout'),
    path('add_product', views.add_product, name='add_product'),
    path('add_category', views.add_category, name='add_category'),
    path('delete_category/<category_id>', views.delete_category, name='delete_category'),
    path('block_user/<user_id>', views.block_user, name='block_user'),
    path('edit_product/<int:product_id>', views.edit_product, name='edit_product'),
    path('delete_product/<product_id>', views.delete_product, name='delete_product'),
    path('edit_category/<int:category_id>', views.edit_category, name='edit_category'),
    path('variation_management',views.variation_management, name='variation_management'),
    path('order_management',views.order_management, name='order_management'),
    path('placed/<order_id>',views.placed, name='placed'),
    path('cancelled/<order_id>',views.cancelled, name='cancelled'),
    path('delivered/<order_id>',views.delivered, name='delivered'),
    path('product_reports',views.product_reports, name='product_reports'),
    path('export_pdf',views.export_pdf, name='export_pdf'),
    path('add_variation', views.add_variation, name='add_variation'),
    path('edit_variation/<product_id>', views.edit_variation, name='edit_variation'),
    path('delete_variation/<product_id>', views.delete_variation, name='delete_variation'),
    path('sales_report',views.sales_report, name='sales_report'),
    path('exportsales_pdf', views.exportsales_pdf, name='exportsales_pdf'),
    path('unblock_user/<user_id>', views.unblock_user, name='unblock_user'),
]
