# Generated by Django 4.0.6 on 2022-08-08 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_variation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variation',
            name='variation_category',
            field=models.CharField(choices=[('power', 'power'), ('size', 'size')], max_length=100),
        ),
    ]
