# Generated by Django 4.0.6 on 2022-08-03 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_alter_category_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'cate', 'verbose_name_plural': 'categories'},
        ),
    ]
