# Generated by Django 4.0.6 on 2022-09-01 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_orderproduct_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('New', 'New'), ('Order Placed', 'Order Placed'), ('Delivered', 'Delivered'), ('Cancelled', 'Cancelled')], default='New', max_length=100),
        ),
    ]
